package ru.boringowl.myroadmapapp.presentation.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006b5e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF76f8e3)
val md_theme_light_onPrimaryContainer = Color(0xFF00201b)
val md_theme_light_secondary = Color(0xFF4a635e)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcde8e1)
val md_theme_light_onSecondaryContainer = Color(0xFF06201b)
val md_theme_light_tertiary = Color(0xFF446179)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc9e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e31)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafdfa)
val md_theme_light_onBackground = Color(0xFF191c1b)
val md_theme_light_surface = Color(0xFFfafdfa)
val md_theme_light_onSurface = Color(0xFF191c1b)
val md_theme_light_surfaceVariant = Color(0xFFdae5e1)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4946)
val md_theme_light_outline = Color(0xFF6e7976)
val md_theme_light_inverseOnSurface = Color(0xFFeff1ef)
val md_theme_light_inverseSurface = Color(0xFF2e3130)
val md_theme_light_inversePrimary = Color(0xFF56dbc7)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF56dbc7)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF76f8e3)
val md_theme_dark_secondary = Color(0xFFb1ccc6)
val md_theme_dark_onSecondary = Color(0xFF1c3530)
val md_theme_dark_secondaryContainer = Color(0xFF334b46)
val md_theme_dark_onSecondaryContainer = Color(0xFFcde8e1)
val md_theme_dark_tertiary = Color(0xFFaccae5)
val md_theme_dark_onTertiary = Color(0xFF143348)
val md_theme_dark_tertiaryContainer = Color(0xFF2d4a60)
val md_theme_dark_onTertiaryContainer = Color(0xFFc9e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1b)
val md_theme_dark_onBackground = Color(0xFFe1e3e1)
val md_theme_dark_surface = Color(0xFF191c1b)
val md_theme_dark_onSurface = Color(0xFFe1e3e1)
val md_theme_dark_surfaceVariant = Color(0xFF3f4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec9c5)
val md_theme_dark_outline = Color(0xFF899390)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1b)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e1)
val md_theme_dark_inversePrimary = Color(0xFF006b5e)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF51a496)
val error = Color(0xFFba1b1b)